export { default as Home } from './home'
export { default as PressButton } from './press-button'
export { default as Footer } from './footer'
export { default as Popup } from './popup'
export { default as SidePanel } from './side-panel'